try:
    from .duck_encode_node import NODE_CLASS_MAPPINGS as STEG_NODES, NODE_DISPLAY_NAME_MAPPINGS as STEG_DISPLAY
    from .duck_decode_node import NODE_CLASS_MAPPINGS as DECODE_NODES, NODE_DISPLAY_NAME_MAPPINGS as DECODE_DISPLAY
    NODE_CLASS_MAPPINGS = {**STEG_NODES, **DECODE_NODES}
    NODE_DISPLAY_NAME_MAPPINGS = {**STEG_DISPLAY, **DECODE_DISPLAY}
except Exception:
    NODE_CLASS_MAPPINGS = {}
    NODE_DISPLAY_NAME_MAPPINGS = {}

WEB_DIRECTORY = "./js"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
